definitions:
  request.RegisterParam:
    properties:
      address:
        description: 地址
        type: string
      birthday:
        description: 生日
        type: string
      email:
        description: 邮箱
        type: string
      nickName:
        description: 昵称
        maxLength: 32
        minLength: 3
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机号码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - nickName
    - password
    - phone
    - username
    type: object
info:
  contact: {}
paths:
  /v1/user/changePassword:
    post:
      consumes:
      - application/json
      description: 更改密码
      operationId: /v1/user/changePassword
      produces:
      - application/json
      responses: {}
      summary: 更改密码
      tags:
      - SysUser
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      operationId: /v1/user/login
      produces:
      - application/json
      responses: {}
      summary: 登录
      tags:
      - SysUser
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /v1/user/register
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterParam'
      produces:
      - application/json
      responses: {}
      summary: 用户注册
      tags:
      - SysUser
swagger: "2.0"
